crm:
  service:
    url: https://virginvoyages--dev.cs67.my.salesforce.com
    version: v40.0
  username: ednZfc2FpbG9yX2FwaUB2aXJnaW52b3lhZ2VzLmNvbS5kZXY=
  password: 9VmlyZ2luNDU2
  client-id: 3MVG99E3Ry5mh4zobSw34jlYQ4PMrCJIRM1qJSjiUkfO1orEbi9U.0mFX2XHOHt8goNgpW.MPqei3dgK7YrC8
  client-secret: 3603309126782682404
  
crossreference:
  service:
    url: http://10.3.100.251:31435/xref-api/v1 
